apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qlhaj9kv9-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/qlhaj9kv9-dotnet-basic-gitops